### ISSUE TITLE
Make db accessible from host

### ISSUE THREAD

**Issue by eleftrik** [ceronem/laravel-compose#5]
In `docker-compose.yml` file could be useful to have

```
services:
  db:
    expose:
      - "3306"
    ports:
      - 3306:3306

```

That way, it would be possible to
- connect to the db container from the host, for example via `mysql` command or with applications such as TablePlus, SequelPro, HeidiSQL, etc.
- execute `artisan` commands directly from the host (for example `php artisan make:migration Foo`); of course, this approach requires a local working PHP installation and adding `db 127.0.0.1` to `/etc/hosts` file (assuming `DB_HOST=db` in `.env` file)
